name: app_tarefas
description: Gestão de tarefas com fotos anexadas.
publish_to: none
version: 1.0.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.1.2
  path_provider: ^2.1.4
  path: ^1.9.0
  http: ^1.2.2
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true